name: Deploy to ECR

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Push Image
    runs-on: windows-2022

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./build/git_update.sh -v major
      

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: winows-images
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          docker build -t sdk:bmo .
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Tag the Docker Image Locally
        run: docker tag 975148384510.dkr.ecr.ca-central-1.amazonaws.com/winows-images:base_img sdk:bmo

      - name: Create Local Docker Image
        run: docker build -t sdk1:bmo .

      - name: Run Docker Container
        run: docker run -d --name sdkbmo1 sdk1:bmo

      - name: List Local Docker Images
        run: docker images
      
      - name: List Local Docker Images
        run: docker images