name: Deploy to ECR

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Push Image
    runs-on: windows-2022

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: winows-images
          IMAGE_TAG: winTest2Image
        run: |
          docker build -t sdk:bmo .
          docker tag sdk:bmo 975148384510.dkr.ecr.ca-central-1.amazonaws.com/winows-images:winTest2Image
          docker push 975148384510.dkr.ecr.ca-central-1.amazonaws.com/winows-images:winTest2Image

      - name: Tag the Docker Image Locally
        run: docker tag 975148384510.dkr.ecr.ca-central-1.amazonaws.com/winows-images:winTest2Image sdk:bmo

      - name: Create Local Docker Image
        run: docker build -t sdk1:bmo .

      - name: Run Docker Container
        run: docker run -d --name sdkbmo1 sdk1:bmo

      - name: List Local Docker Images
        run: docker images
      
      - name: List Local Docker Images
        run: docker images